// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mkaaasieezgnuhhsskra.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1rYWFhc2llZXpnbnVoaHNza3JhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNzEyMDgsImV4cCI6MjA3Mzk0NzIwOH0.mItaH_0nHToj2lH4ZOUf15Hw0GEb9w2LryWXxp_sT9I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});